# Generated by Django 4.0.1 on 2022-02-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
                ('grade', models.CharField(max_length=3, verbose_name='Grade')),
                ('major', models.CharField(max_length=50, verbose_name='Major Subjects')),
            ],
        ),
    ]
